# buildinfo.mk - Build metadata generation
# Include this file in your Makefile and call 'generate-buildinfo' target

# Version format:
# Without git: VERSION@TIMESTAMP
# With git, clean tree: VERSION@branch-revision-commit_timestamp (no Built line)
# With git, dirty tree: VERSION@branch-HEAD (Built line shows current time)
# If -DRELEASE_VERSION specified: VERSION only

FALLBACK_NAME ?= unknown
FALLBACK_REV  ?= unknown
VERSION_FILE ?= VERSION

INSIDE_WT := $(shell command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree 2>/dev/null || echo false)

# Read base version from VERSION file
ifneq ($(wildcard $(VERSION_FILE)),)
  BASE_VERSION := $(shell cat $(VERSION_FILE))
else
  BASE_VERSION := $(FALLBACK_NAME)
endif

# Check if RELEASE_VERSION is defined (via -DRELEASE_VERSION in CFLAGS or as make variable)
ifdef RELEASE_VERSION
  GITVER := $(BASE_VERSION)
  BRANCH_NAME := release
  REV := $(BASE_VERSION)
  REV_FULL := $(BASE_VERSION)
  DIRTY_FLAG := false
  TIMESTAMP := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
else ifeq ($(INSIDE_WT),true)
  # Inside git repository
  BRANCH_NAME := $(shell git symbolic-ref --short -q HEAD 2>/dev/null || echo detached)
  REV_FULL := $(shell git rev-parse HEAD)
  DIRTY_FLAG := $(shell test -n "$$(git status --porcelain 2>/dev/null)" && echo "true" || echo "false")
  TIMESTAMP := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
  COMMIT_TIMESTAMP := $(shell TZ=UTC git log -1 --format="%cd" --date=format-local:"%Y-%m-%dT%H:%M:%SZ" HEAD)

  ifeq ($(DIRTY_FLAG),true)
    # Dirty tree: VERSION@branch-HEAD (no timestamp - it's in Built line)
    REV := HEAD
    GITVER := $(BASE_VERSION)@$(BRANCH_NAME)-HEAD
  else
    # Clean tree: VERSION@branch-revision-commit_timestamp
    REV := $(shell git rev-parse --short=8 HEAD)
    GITVER := $(BASE_VERSION)@$(BRANCH_NAME)-$(REV)-$(COMMIT_TIMESTAMP)
  endif
else
  # Not in git repository: VERSION@TIMESTAMP
  BRANCH_NAME := unknown
  REV := unknown
  REV_FULL := unknown
  DIRTY_FLAG := unknown
  TIMESTAMP := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
  GITVER := $(BASE_VERSION)@$(TIMESTAMP)
endif

# Capture build environment metadata
BUILD_DATE := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
BUILD_HOST := $(shell hostname)
BUILD_USER := $(shell whoami)
BUILD_OS := $(shell uname -s)
BUILD_ARCH := $(shell uname -m)

# CC_VERSION will be evaluated when generate-buildinfo is called
# so it picks up the CC variable from the parent Makefile

# SBOM (Software Bill of Materials) Configuration
# These can be overridden in the parent Makefile
SBOM_FILE ?= SBOM.spdx
SBOM_PACKAGE_NAME ?= $(shell basename $(PWD))
SBOM_SPDX_LICENSE ?= NOASSERTION
SBOM_SUPPLIER ?= NOASSERTION
SBOM_HOMEPAGE ?= NOASSERTION

# Check if SBOM file exists
SBOM_EXISTS := $(shell test -f $(SBOM_FILE) && echo yes || echo no)

.PHONY: print-version
print-version:
	@echo $(GITVER)

# Generate buildinfo.c with all metadata
.PHONY: generate-buildinfo
generate-buildinfo:
	@mkdir -p $(BUILDDIR)
	@echo "/* Auto-generated by buildinfo.mk - do not edit */" > $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "#include <stdio.h>" >> $(BUILDDIR)/buildinfo.c
	@echo "#include <string.h>" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_base_version = \"$(BASE_VERSION)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_full_version = \"$(GITVER)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_commit_short = \"$(REV)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_commit_full = \"$(REV_FULL)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_timestamp = \"$(BUILD_DATE)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_dirty = \"$(DIRTY_FLAG)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_host = \"$(BUILD_HOST)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_user = \"$(BUILD_USER)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_os = \"$(BUILD_OS)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_arch = \"$(BUILD_ARCH)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *build_compiler = \"$(shell $(CC) --version 2>/dev/null | head -n1)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "/* SBOM metadata */" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *sbom_package_name = \"$(SBOM_PACKAGE_NAME)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *sbom_spdx_license = \"$(SBOM_SPDX_LICENSE)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *sbom_supplier = \"$(SBOM_SUPPLIER)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "const char *sbom_homepage = \"$(SBOM_HOMEPAGE)\";" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "/* Structured metadata in custom ELF/Mach-O section */" >> $(BUILDDIR)/buildinfo.c
	@printf "#ifdef __APPLE__\n" >> $(BUILDDIR)/buildinfo.c
	@printf "__attribute__((section(\"__TEXT,__buildinfo\")))\n" >> $(BUILDDIR)/buildinfo.c
	@printf "#else\n" >> $(BUILDDIR)/buildinfo.c
	@printf "__attribute__((section(\".buildinfo\")))\n" >> $(BUILDDIR)/buildinfo.c
	@printf "#endif\n" >> $(BUILDDIR)/buildinfo.c
	@echo "__attribute__((used))" >> $(BUILDDIR)/buildinfo.c
	@echo "const char build_metadata[] =" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"base_version=$(BASE_VERSION)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"full_version=$(GITVER)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"commit=$(REV_FULL)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"commit_short=$(REV)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"timestamp=$(BUILD_DATE)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"dirty=$(DIRTY_FLAG)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"build_host=$(BUILD_HOST)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"build_user=$(BUILD_USER)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"build_os=$(BUILD_OS)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"build_arch=$(BUILD_ARCH)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    \"compiler=$(shell $(CC) --version 2>/dev/null | head -n1)\\\\n\";\n" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "/* SBOM metadata in custom ELF/Mach-O section */" >> $(BUILDDIR)/buildinfo.c
	@printf "#ifdef __APPLE__\n" >> $(BUILDDIR)/buildinfo.c
	@printf "__attribute__((section(\"__TEXT,__sbom\")))\n" >> $(BUILDDIR)/buildinfo.c
	@printf "#else\n" >> $(BUILDDIR)/buildinfo.c
	@printf "__attribute__((section(\".sbom\")))\n" >> $(BUILDDIR)/buildinfo.c
	@printf "#endif\n" >> $(BUILDDIR)/buildinfo.c
	@echo "__attribute__((used))" >> $(BUILDDIR)/buildinfo.c
	@echo "const char sbom_metadata[] =" >> $(BUILDDIR)/buildinfo.c
	@if [ -f $(SBOM_FILE) ]; then \
		awk '{ \
			gsub(/\\/, "\\\\"); \
			gsub(/"/, "\\\""); \
			printf "    \"%s\\n\"\n", $$0; \
		} END { \
			printf "    \"\";\n"; \
		}' $(SBOM_FILE) >> $(BUILDDIR)/buildinfo.c; \
	else \
		printf "    \"SPDXVersion: SPDX-2.3\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"DataLicense: CC0-1.0\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"SPDXID: SPDXRef-DOCUMENT\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"DocumentName: $(SBOM_PACKAGE_NAME)-sbom\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"DocumentNamespace: https://example.org/sbom/$(SBOM_PACKAGE_NAME)-$(BASE_VERSION)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"Creator: Tool: buildinfo\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"Created: $(BUILD_DATE)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"PackageName: $(SBOM_PACKAGE_NAME)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"SPDXID: SPDXRef-Package\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"PackageVersion: $(BASE_VERSION)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"PackageSupplier: $(SBOM_SUPPLIER)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"PackageLicenseDeclared: $(SBOM_SPDX_LICENSE)\\\\n\"\n" >> $(BUILDDIR)/buildinfo.c; \
		printf "    \"\";\n" >> $(BUILDDIR)/buildinfo.c; \
	fi
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "void print_version_info(void) {" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"Version: %%s\\\\n\", build_full_version);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Base version: %%s\\\\n\", build_base_version);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Commit: %%s\\\\n\", build_commit_full);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    if (strcmp(build_dirty, \"true\") == 0) {\n" >> $(BUILDDIR)/buildinfo.c
	@printf "        printf(\"  Built: %%s\\\\n\", build_timestamp);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    }\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Compiler: %%s\\\\n\", build_compiler);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Platform: %%s/%%s\\\\n\", build_os, build_arch);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "}\n" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "void print_sbom_info(void) {" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"SBOM Information:\\\\n\");\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Package: %%s\\\\n\", sbom_package_name);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Version: %%s\\\\n\", build_base_version);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  License: %%s\\\\n\", sbom_spdx_license);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"  Supplier: %%s\\\\n\", sbom_supplier);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "}\n" >> $(BUILDDIR)/buildinfo.c
	@echo "" >> $(BUILDDIR)/buildinfo.c
	@echo "void print_sbom_full(void) {" >> $(BUILDDIR)/buildinfo.c
	@printf "    printf(\"%%s\\\\n\", sbom_metadata);\n" >> $(BUILDDIR)/buildinfo.c
	@printf "}\n" >> $(BUILDDIR)/buildinfo.c
